project:
  type: website

website:
  page-navigation: true
  title: "SCoRT"
  description: "Homepage for 'Short Course on R Tools', Summer 2025."
  site-url: "https://tinyurl.com/SCiRT"

  repo-url: https://github.com/mmadoliat/SCoRT/
  repo-actions: [edit, issue]

  open-graph: true
  twitter-card:
    creator: "@mmadoliat"
    image: "images/twitter-card.png"

  sidebar:
    background: "#FFCC00" # MU Yellow
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/mmadoliat/SCoRT/
        text: "GitHub organization"
      - icon: code-square
        href: https://tinyurl.com/SCiRT
        text: "TinyURL"
      - icon: person-fill
        href: https://tinyurl.com/RS-dna
        text: "dna Rstudio"

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: index.qmd
            text: Schedule
      - section: "Slides"
        contents:
          - href: slides/Topic1.qmd
            text: OOP in R
          - href: slides/Topic2.qmd
            text: Shiny
          - href: slides/Topic3.qmd
            text: RCpp
          - href: slides/Topic4.qmd
            text: Python in R
          - href: slides/Topic5.qmd
            text: R package
          - href: slides/Topic6.qmd
            text: GitHub / CRAN submission
          - href: slides/Topic7.qmd
            text: Deep Learning in R
      - section: "Hands-on / HW"
        contents:
          - href: hands-on/HO1.qmd
            text: OOP in R
          - href: hands-on/HO2.qmd
            text: Shiny
          - href: hands-on/HO3.qmd
            text: RCpp
          - href: hands-on/HW1.qmd
            text: First Week HW
          - href: hands-on/reticulate/
            text: Python in R
          - href: hands-on/packages/
            text: R Package
          - href: hands-on/git/
            text: GitHub
      - section: "Miscellaneous"
        contents:
          - href: course-links.qmd
            text: Useful links
          - href: misc/cheatsheets.qmd
            text: Cheatsheets

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Mehdi Maadooliat"
    background: "#FFCC00" # Arylide Yellow
    
format:
  html:
    theme:
      light: [cosmo, style/mu.scss]
      dark: [cosmo, style/mu.scss, style/dark.scss]
    linkcolor: "#003366" # Glossy Grape
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"
    highlight-style: a11y-dark
    code-link: true

execute:
  freeze: auto

editor: visual
