---
title: "Short Course on R Tools - (SCoRT)"
execute: 
  freeze: false
---

This page contains an outline of the topics, content, and assignments for the short course. Note that this schedule will be updated as we progress, and the timeline of topics and assignments might be updated throughout the course.

```{r}
#| echo: false
#| message: false
#| warning: false
library(googlesheets4)
library(gt)
library(tidyverse)
gs4_deauth()
d <- read_sheet("https://docs.google.com/spreadsheets/d/1FokubeE-f4Q71plkCsY84ZF_-2noo6TywXoGo2LItsM/edit?usp=sharing")
```

```{r}
#| echo: false

d[d$date < max(today()+321, as.Date("2025-02-04")),] |>
  #filter(!is.na(session)) |>
  select(-dow, -session) |>
  mutate(date = as.Date(date)) |>
  relocate(due, .after = code) |>
  gt() |>
  fmt_date(date, date_style = 31) |>
  sub_missing(columns = c(week, topic, materials, code, due), missing_text = "") |>
  cols_align(
    align = "center", 
    columns = c(week)
  ) |>
  cols_align(
    align = "right", 
    columns = c(date)
  ) |>
  cols_align(
    align = "left", 
    columns = c(topic, materials, code, due)
  ) |>
  tab_style(
    style = cell_borders(
      sides = "right",
      color = "#D3D3D3",
      style = "solid"
    ),
    locations = cells_body(
      columns = c(date, topic, materials, code)
    )
  ) |>
  fmt_markdown(
    columns = c(topic, materials, code, due)
  ) |>
  cols_width(
    week ~ px(45),
    date ~ px(100), 
    topic ~ px(300),
    materials ~ px(150),
    code ~ px(40),
    due ~ px(300)
  ) |>
  cols_label_with(fn = function(x) {
      janitor::make_clean_names(x, case = "title") |>
        toupper() |>
        stringr::str_replace_all("^|$", "**") |>
        md()
    }) |>
  tab_options(table.font.size = 13) |>
  opt_row_striping()
```
